source 'https://rubygems.org'
gem 'pry'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'rspec'
gem 'feedzirra'
gem 'sanitize'

gem 'rgeo'
gem 'rgeo-activerecord'
gem 'pg'
gem 'activerecord-postgis-adapter'
