require './lib/spatio'

require_relative 'models/state'
require_relative 'models/community'
require_relative 'models/district'
require_relative 'models/locality'
require_relative 'models/format_definition'
require_relative 'models/import'
require_relative 'models/namespace'
require_relative 'models/field'
